Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: D:\GitHub\vision-serverless\process_s3_csv
      Runtime: python3.8